name = "abeai-proxy"
main = "index.js"
compatibility_date = "2024-03-27"

kv_namespaces = [
  { binding = "ABEAI_KV", id = "5084daa8615147bab2771668a729620d" }
]

# Remove custom_domain and use zone_id instead
routes = [
  { pattern = "api.abeai.health/*", zone_id = "YOUR_ZONE_ID" } # ← Get from Cloudflare DNS
]

# Disable build steps
[build]
upload.format = "modules"
command = "echo 'No build needed'" # ← Bypasses npm errors
