# PROPERLY FORMATTED ERROR-FREE CONFIG
name = "abeai-proxy"
main = "index.js"
compatibility_date = "2024-03-27"

# KV Storage (original binding)
kv_namespaces = [
  { binding = "ABEAI_KV", id = "5084daa8615147bab2771668a729620d" }
]

# Routes (original)
routes = [
  { pattern = "api.abeai.health/*", custom_domain = true }
]

# Performance limits
[limits]
cpu_ms = 5000
memory = 128

[build]
upload.format = "modules"
upload.main = "./index.js"

# Environment variables (simplified)
[vars]
ENVIRONMENT = "production"
MAX_HISTORY_ITEMS = "10"
