name = "abeai-proxy"
main = "src/index.js"
compatibility_date = "2023-03-27"
usage_model = "bundled"
workers_dev = true

[[kv_namespaces]]
binding = "ABEAI_KV"
id = "508da4aa8615147bab277168a729620d"
